site_name: Singularity Daily
site_url: https://www.singularitydaily.com/
site_author: leejunyoung399
site_description: 특이점, AI, 생명 연장 등 최신 기술 동향을 수집하고 요약합니다.
theme:
  name: material
  language: ko
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
  - navigation.top
  - navigation.tracking
  - navigation.expand
  - content.code.copy
use_directory_urls: false
markdown_extensions:
- admonition
- toc:
    permalink: ¶
- footnotes
- meta
extra_css:
- stylesheets/extra.css
plugins:
- search
nav:
- 홈: index.md
- 블로그: blog/index.md
- 기사: articles/index.md
- 키워드:
  - AGI: keywords/AGI/index.md
  - AGI - 새로운 결과: keywords/AGI - 새로운 결과/index.md
  - AI drug discovery: keywords/AI drug discovery/index.md
  - AI drug discovery - 새로운 결과: keywords/AI drug discovery - 새로운 결과/index.md
  - Anti-aging therapeutics: keywords/Anti-aging therapeutics/index.md
  - Anti-aging therapeutics - 새로운 결과: keywords/Anti-aging therapeutics - 새로운 결과/index.md
  - Cellular reprogramming: keywords/Cellular reprogramming/index.md
  - Cellular reprogramming - 새로운 결과: keywords/Cellular reprogramming - 새로운 결과/index.md
  - Humanoid Robot: keywords/Humanoid Robot/index.md
  - Longevity research: keywords/Longevity research/index.md
  - Longevity research - 새로운 결과: keywords/Longevity research - 새로운 결과/index.md
  - NMN: keywords/NMN/index.md
  - NMN - 새로운 결과: keywords/NMN - 새로운 결과/index.md
  - Nanobot: keywords/Nanobot/index.md
  - Rapamycin: keywords/Rapamycin/index.md
  - Rapamycin - 새로운 결과: keywords/Rapamycin - 새로운 결과/index.md
  - Senolytics: keywords/Senolytics/index.md
  - Senolytics - 새로운 결과: keywords/Senolytics - 새로운 결과/index.md
  - Telomere extension: keywords/Telomere extension/index.md
  - Telomere extension - 새로운 결과: keywords/Telomere extension - 새로운 결과/index.md
